# Generated by Django 2.2.4 on 2019-09-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_auto_20150528_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dontsendentry',
            name='to_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='host',
            field=models.CharField(max_length=100, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is default configuration'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Configuration name'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='port',
            field=models.IntegerField(verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='use_tls',
            field=models.BooleanField(default=False, verbose_name='Enable TLS'),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='message',
            name='priority',
            field=models.CharField(choices=[('1', 'high'), ('2', 'medium'), ('3', 'low'), ('4', 'deferred')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='priority',
            field=models.CharField(choices=[('1', 'high'), ('2', 'medium'), ('3', 'low'), ('4', 'deferred')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='result',
            field=models.CharField(choices=[('1', 'success'), ('2', "don't send"), ('3', 'failure')], max_length=1),
        ),
    ]
